parameters:
  crates: []

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: stable

  - ${{ each crate in parameters.crates }}:
    - script: cargo test
      displayName: cargo test -p ${{ crate }}
      workingDirectory: $(Build.SourcesDirectory)/${{ crate }}
