# Patch dependencies to run all tests against versions of the crate in the
# repository.
[patch.crates-io]
tower = { path = "tower" }
tower-layer = { path = "tower-layer" }
tower-service = { path = "tower-service" }
tower-test = { path = "tower-test" }
