name: Deploy API Documentation

on:
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
      - name: Generate documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --no-deps --all-features
          # Tower uses nightly-only RustDoc features
          toolchain: nightly
        env:
          # Enable the RustDoc `#[doc(cfg(...))]` attribute.
          RUSTDOCFLAGS: --cfg docsrs
      - name: Deploy documentation
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: target/doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

